# Default values for flair-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: flairbi/flair-registry
  tag: v7.0.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# Secret mount to be used if any secret files are needed to be added to the container during startup
# secretMountName: flair-secret

service:
  type: ClusterIP
  eurekaPort: 8761
  configPort: 8762

env:
  JHIPSTER_SLEEP: 0
  SPRING_PROFILES_ACTIVE: prod
  BITBUCKET_URI: https://github.com/viz-centric/flair-config.git

# Can be used if you want to set environment variables from a secret
# The key names need to be the same as the environment variables you want to set
# You would have to make sure the secret is created with the same key names as the environment variables you would like to set

secretEnv:
  name: flair-secret
  keys: []
#     - FLAIR_SECRET_USERNAME
#     - FLAIR_SECRET_PASSWORD

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

annotations:
  sidecar.istio.io/rewriteAppHTTPProbers: "true"
